const n = (key, label, min = 0, max = 100, when) => ({ key, label, type: 'number', min, max, when });
const c = (key, label, when) => ({ key, label, type: 'color', when });
const b = (key, label, when) => ({ key, label, type: 'boolean', when });
const t = (key, label, max = 80, when) => ({ key, label, type: 'text', max, when });
const s = (key, label, options, when) => ({ key, label, type: 'select', options: Object.entries(options).map(([value, label]) => ({ value, label })), when });
const i = (key, label, when) => ({ key, label, type: 'image', when });
const align = { left: '左对齐', center: '居中', right: '右对齐' };
export const surfaceFields = [s('mode', '背景类型', { solid: '纯色', gradient: '渐变', image: '图片' }), c('color', '背景色 / 图片底色'),
  c('color2', '渐变结束色', v => v.mode === 'gradient'), n('angle', '渐变角度', 0, 360, v => v.mode === 'gradient'),
  i('image', '背景图片', v => v.mode === 'image'), s('imageFit', '图片缩放', { cover: '铺满裁切', contain: '完整显示', '100% 100%': '拉伸铺满' }, v => v.mode === 'image'), s('imagePosition', '图片位置', { center: '居中', top: '顶部', bottom: '底部', left: '左侧', right: '右侧' }, v => v.mode === 'image'),
  n('borderWidth', '边框宽度', 0, 10), s('borderStyle', '边框样式', { solid: '实线', dashed: '虚线', dotted: '点线' }, v => v.borderWidth > 0), c('borderColor', '边框颜色', v => v.borderWidth > 0), n('radius', '圆角', 0, 100, v => v.shape !== 'medal'),
  b('shadow', '显示阴影'), c('shadowColor', '阴影颜色', v => v.shadow), n('shadowBlur', '阴影模糊', 0, 60, v => v.shadow), n('shadowX', '阴影水平偏移', -30, 30, v => v.shadow), n('shadowY', '阴影垂直偏移', -30, 30, v => v.shadow)];
export const layoutFields = [b('followTheme', '价格与按钮跟随商城主题色'),s('layout', '榜单布局', { list: '纵向列表', podium: '前三名领奖台 + 列表', grid: '商品网格' }), n('columns', '网格列数', 1, 3, v => v.layout === 'grid'),
  s('cardLayout', '列表卡片结构', { standard: '普通图文', commerce: '图文 + 价格底栏', retail: '图文 + 行内价格', shop: '店铺口碑' }, v => v.layout === 'list'), n('panelPadding', '榜单内部留白', 0, 40), n('gap', '卡片间距', 0, 40), n('padding', '卡片内边距', 0, 40), n('imageGap', '卡片元素间距', 0, 40), s('badgePosition', '名次位置', { side: '前置（左侧 / 顶部）', image: '图片左上角', corner: '卡片左上角' }), n('podiumLift', '冠军抬高距离', 0, 50, v => v.layout === 'podium')];
export const headerFields = [n('padding', '榜头内边距', 0, 60), s('align', '榜头对齐', align), n('gap', '榜头元素间距', 0, 40), i('icon', '榜头装饰图标'), n('iconSize', '图标大小', 12, 100, v => !!v.icon),
  b('showOverline', '显示眉题'), t('overline', '眉题文字', 80, v => v.showOverline), c('overlineColor', '眉题颜色', v => v.showOverline), n('overlineSize', '眉题字号', 8, 32, v => v.showOverline), n('overlineSpacing', '眉题字间距', 0, 10, v => v.showOverline),
  c('titleColor', '榜单标题颜色', (_, ctx) => ctx.showTitle), n('titleSize', '榜单标题字号', 12, 40, (_, ctx) => ctx.showTitle), b('titleBold', '榜单标题加粗', (_, ctx) => ctx.showTitle),
  t('description', '榜单说明覆盖（留空使用数据源）', 300, (_, ctx) => ctx.showDescription), c('descriptionColor', '说明文字颜色', (_, ctx) => ctx.showDescription), n('descriptionSize', '说明文字字号', 8, 24, (_, ctx) => ctx.showDescription),
  t('moreText', '完整榜单入口文字', 20, (_, ctx) => ctx.showMore), c('moreColor', '入口文字颜色', (_, ctx) => ctx.showMore), n('moreSize', '入口文字字号', 8, 24, (_, ctx) => ctx.showMore)];
export const imageFields = [n('imageWidth', '列表图片宽度', 24, 160, (_, ctx) => ctx.layout !== 'grid'), n('imageHeight', '列表图片高度', 24, 180, (_, ctx) => ctx.layout !== 'grid'),
  n('gridImageHeight', '网格图片高度', 40, 260, (_, ctx) => ctx.layout === 'grid'), n('podiumImageSize', '领奖台图片大小', 24, 100, (_, ctx) => ctx.layout === 'podium'),
  s('imageFit', '商品图片缩放', { contain: '完整显示', cover: '铺满裁切' }), n('imageRadius', '商品图片圆角', 0, 90), c('imageBackground', '图片底色'), n('imageBorderWidth', '图片边框宽度', 0, 8), c('imageBorderColor', '图片边框颜色', v => v.imageBorderWidth > 0)];
export const textFields = [n('nameSize', '名称字号', 10, 28, v => v.showName), b('nameBold', '名称加粗', v => v.showName), n('nameLines', '名称最多行数', 1, 4, v => v.showName), { ...n('lineHeight', '名称行高倍数', 1, 2.5, v => v.showName), precision: 1, step: 0.1 },
  n('gap', '内容行间距', 0, 30), n('priceSize', '价格字号', 10, 32, (v, ctx) => v.showPrice && !ctx.isShop), b('priceBold', '价格加粗', (v, ctx) => v.showPrice && !ctx.isShop), t('pricePrefix', '价格前缀', 10, (v, ctx) => v.showPrice && !ctx.isShop),
  n('metaSize', '指标字号', 8, 24, (v, ctx) => v.showSales || v.showReviews || v.showRating || ctx.showScore || (v.showProductCount && ctx.isShop)),
  t('salesLabel', '成交指标名称', 20, v => v.showSales), t('reviewsLabel', '评价指标名称', 20, v => v.showReviews), t('ratingLabel', '好评率指标名称', 20, v => v.showRating), t('productCountLabel', '在售商品指标名称', 20, (v, ctx) => v.showProductCount && ctx.isShop), t('scoreLabel', '综合分指标名称', 20, (_, ctx) => ctx.showScore)];
export const buttonFields = [t('buttonText', '按钮文字', 20), c('buttonColor', '按钮文字颜色'), c('buttonBackground', '按钮背景色', (_, ctx) => !ctx.followTheme), n('buttonBorderWidth', '按钮边框宽度', 0, 8), c('buttonBorderColor', '按钮边框颜色', (v, ctx) => v.buttonBorderWidth > 0 && !ctx.followTheme), n('buttonRadius', '按钮圆角', 0, 50), n('buttonSize', '按钮字号', 10, 24), n('buttonPaddingX', '按钮左右内边距', 0, 30), n('buttonPaddingY', '按钮上下内边距', 0, 20)];
export const badgeFields = [b('visible', '显示名次标识'), s('shape', '名次标识样式', { text: '纯数字文字', ribbon: '绶带', medal: '圆形奖章', pill: '圆角标签', square: '方形角标', image: '自定义图片', shield: '盾形奖牌', crown: '皇冠旗标', flag: '竖向TOP旗标' }, v => v.visible),
  i('customImage', '名次标识图片', v => v.visible && v.shape === 'image'), b('showText', '图片叠加名次文字', v => v.visible && v.shape === 'image'),
  t('text', '名次文案（{rank}为名次）', 40, v => v.visible && (v.shape !== 'image' || v.showText || !v.customImage)), c('textColor', '名次文字颜色', v => v.visible && (v.shape !== 'image' || v.showText || !v.customImage)), n('fontSize', '名次字号', 8, 40, v => v.visible && !v.stacked && (v.shape !== 'image' || v.showText || !v.customImage)), b('stacked', 'TOP与数字分行', v => v.visible && (v.shape !== 'image' || v.showText || !v.customImage)), n('labelSize', 'TOP前缀字号', 6, 20, v => v.visible && v.stacked && /.+\{rank/.test(v.text) && (v.shape !== 'image' || v.showText || !v.customImage)), n('numberSize', '名次数字字号', 10, 40, v => v.visible && v.stacked && (v.shape !== 'image' || v.showText || !v.customImage)), b('bold', '名次文字加粗', v => v.visible && (v.shape !== 'image' || v.showText || !v.customImage)), n('width', '名次标识宽度', 16, 120, v => v.visible), n('height', '名次标识高度', 16, 100, v => v.visible)];
export const rankTextFields = [c('titleColor', '名称 / 榜名颜色', (_, ctx) => ctx.detail || ctx.content.showName), c('priceColor', '价格颜色', (_, ctx) => !ctx.detail && !ctx.isShop && ctx.content.showPrice && !ctx.followTheme), c('metaColor', '指标 / 名次说明颜色', (_, ctx) => ctx.detail || ctx.content.showSales || ctx.content.showReviews || ctx.content.showRating || ctx.showScore || (ctx.isShop && ctx.content.showProductCount))];
export const footerFields = [b('show', '显示底部说明'), t('text', '底部说明', 150, v => v.show), c('color', '底部文字颜色', v => v.show), n('fontSize', '底部字号', 8, 24, v => v.show), s('align', '底部文字对齐', align, v => v.show), n('padding', '底部内边距', 0, 40, v => v.show)];
export const emptyFields = [b('hide', '无数据时隐藏组件'), t('text', '空状态文案', 80, v => !v.hide), c('color', '空状态颜色', v => !v.hide), n('fontSize', '空状态字号', 8, 24, v => !v.hide), n('padding', '空状态内边距', 0, 60, v => !v.hide)];
export const detailFields = [c('textColor','榜名与名次颜色'),c('badgeColor','TOP文字颜色'),c('badgeBackground','TOP背景颜色'),t('rankText', '名次文案（{rank}为名次）', 40), b('showShopLabel', '店铺榜显示所属店铺前缀'), t('shopLabel', '所属店铺前缀', 20, v => v.showShopLabel), n('fontSize', '信息字号', 10, 28), b('bold', '榜名加粗'), b('showArrow', '显示跳转箭头'), c('arrowColor', '箭头颜色', v => v.showArrow), n('arrowSize', '箭头大小', 12, 40, v => v.showArrow)];
export const commerceFields = [c('color', '价格底栏底色', (_,ctx) => ctx.cardLayout === 'commerce'), n('paddingX','底栏左右留白',0,30,(_,ctx)=>ctx.cardLayout==='commerce'), n('paddingY','底栏上下留白',0,24,(_,ctx)=>ctx.cardLayout==='commerce'), b('reverse','价格靠右、按钮靠左')];
export const evidenceFields = [s('highlightMetric','突出显示指标',{none:'不突出显示',score:'综合得分',sales:'成交件数',reviews:'评价数',rating:'好评率'}), t('highlightLabel','突出指标文案',20,v=>v.highlightMetric!=='none'), c('highlightColor','突出指标文字颜色',v=>v.highlightMetric!=='none'), c('highlightBackground','突出指标底色',v=>v.highlightMetric!=='none'), n('highlightSize','突出指标字号',10,20,v=>v.highlightMetric!=='none'), n('highlightPadding','突出指标留白',0,16,v=>v.highlightMetric!=='none'), n('highlightRadius','突出指标圆角',0,20,v=>v.highlightMetric!=='none'), b('showStars','显示真实星级评分'), c('starColor','评分颜色',v=>v.showStars), c('starEmptyColor','未填充星星颜色',v=>v.showStars), n('starSize','星星大小',10,24,v=>v.showStars), b('showType','显示店铺类型',(_,ctx)=>ctx.isShop), b('showShopDescription','显示店铺简介',(_,ctx)=>ctx.isShop)];
