<template><el-form label-position="top" size="small" class="ranking-fields"><el-form-item v-for="field in visibleFields" :key="field.key" :label="field.label" :data-field="field.key">
  <el-input-number v-if="field.type === 'number'" :value="value[field.key]" :min="field.min" :max="field.max" :precision="field.precision || 0" :step="field.step || 1" controls-position="right" @input="update(field.key, $event)" />
  <theme-color-picker v-else-if="field.type === 'color'" :value="value[field.key]" @input="update(field.key, $event)" />
  <el-switch v-else-if="field.type === 'boolean'" :value="value[field.key]" @change="update(field.key, $event)" />
  <el-select v-else-if="field.type === 'select'" :value="value[field.key]" @change="update(field.key, $event)"><el-option v-for="option in field.options" :key="option.value" :label="option.label" :value="option.value" /></el-select>
  <div v-else-if="field.type === 'image'" class="rank-image-picker"><img v-if="value[field.key]" :src="value[field.key]" alt="已选择图片" /><el-button size="mini" @click="imageKey = field.key; mediaOpen = true">选择图片</el-button><el-button v-if="value[field.key]" type="text" @click="update(field.key, '')">清除</el-button><el-input :value="value[field.key]" size="mini" maxlength="1000" placeholder="也可输入图片地址" @input="update(field.key, $event)" /></div>
  <el-input v-else :value="value[field.key]" :maxlength="field.max" @input="update(field.key, $event)" />
</el-form-item><el-dialog title="选择排行榜素材" :visible.sync="mediaOpen" width="950px" append-to-body><upload-pictures v-if="mediaOpen" is-choice="单选" @getPic="selectedImage" /></el-dialog></el-form></template>
<script>
import ThemeColorPicker from './ThemeColorPicker';
import UploadPictures from '@/components/uploadPictures';
export default { components: { UploadPictures,ThemeColorPicker }, props: { value: Object, fields: Array, onUpdate: Function, context: { type: Object, default: () => ({}) } }, data() { return { mediaOpen: false, imageKey: '' }; }, computed: { visibleFields() { return this.fields.filter(field => !field.when || field.when(this.value, this.context)); } }, methods: { update(key, value) { if(this.onUpdate)return this.onUpdate(key,value); this.$set(this.value, key, value); if (key === 'shape' && ['pill','square','ribbon','image'].includes(value)) this.$set(this.value, 'radius', { pill: 24, square: 0, ribbon: 6, image: 0 }[value]); }, selectedImage(pic) { this.update(this.imageKey, pic.att_dir); this.mediaOpen = false; } } };
</script>
<style scoped>.ranking-fields{display:grid;grid-template-columns:1fr 1fr;gap:0 12px}.ranking-fields .el-form-item{min-width:0;margin-bottom:16px}.ranking-fields .el-input-number,.ranking-fields .el-select{width:100%}.ranking-fields /deep/ .el-form-item__label{font-size:12px;color:#707784;line-height:20px;padding-bottom:6px}.rank-image-picker{display:flex;flex-wrap:wrap;gap:4px}.rank-image-picker img{width:36px;height:36px;object-fit:contain}.rank-image-picker .el-button{margin:0}.rank-image-picker .el-input{margin-top:4px}</style>
