<template><div ref="frame" class="ranking-canvas" :data-fonts-ready="fontsReady ? 'true' : 'false'" :style="rootStyle"><div v-for="frame in frameList" :key="frame.key" :style="frameBox(frame)" :data-section="frame.section"><div :style="frameStage(frame)"><div class="rc-content-layer"><ranking-canvas-node v-for="node in frame.nodes" :key="node.id" :node="node" :context="nodeContext(frame)" :editing="editing" :selected-id="selectedId" @select="$emit('select',$event)" @action="$emit('action',$event)" /></div><div class="rc-border-layer" aria-hidden="true"><ranking-canvas-node v-for="node in frame.nodes" :key="node.id" :node="node" :context="nodeContext(frame)" :editing="editing" borders-only /></div></div></div><div v-if="editing && fontError" class="rc-font-error">{{fontError}}</div></div></template>
<script>
import RankingCanvasNode from './RankingCanvasNode';
import { rankingCanvasView } from '../../../../shared/rankingCanvasView';
import setting from '@/setting';
const imageUrl=url=>url&&url.startsWith('/')?setting.apiBaseURL.replace(/\/(adminapi|api)\/?$/,'')+url:url;
export default {components:{RankingCanvasNode},mixins:[rankingCanvasView(imageUrl)],mounted(){this.measure();this.observer=new ResizeObserver(this.measure);this.observer.observe(this.$refs.frame);this.loadFont();},beforeDestroy(){if(this.observer)this.observer.disconnect();},watch:{fontResourceKey(){this.loadFont();}},methods:{measure(){if(this.$refs.frame)this.measuredWidth=this.$refs.frame.getBoundingClientRect().width;},async loadFont(){const version=++this.fontLoadVersion;this.fontsReady=false;this.fontError='';try{for(const font of this.fontResources){const face=new FontFace(font.alias,'url('+JSON.stringify(imageUrl(font.url))+')');await face.load();document.fonts.add(face);}}catch(_){if(version===this.fontLoadVersion)this.fontError='字体未能加载，请检查字体地址和跨域权限';}finally{if(version===this.fontLoadVersion)this.fontsReady=true;}}}};
</script>
<style lang="scss">@import '../../../../shared/rankingCanvas.scss';.rc-font-error{padding:10px;color:#c55;background:#fff;font-size:12px}</style>
