const assert=require('node:assert/strict');const {chromium}=require('playwright');const {bundle,install}=require('./theme_component_harness.cjs');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await install(page,bundle('template/admin/src/pages/setting/theme/editTheme/components/CartEditor.vue'));await page.waitForFunction(()=>!editor.loading);await page.locator('.el-loading-mask').waitFor({state:'hidden'});
 const field=page.locator('.cart-form .el-form-item').filter({hasText:'页面背景色'});assert.equal(await field.count(),1,'page background color has an explicit setting');
 const area=await field.boundingBox();assert.ok(area.y>=0 && area.y+area.height<=720,'page color is visible without scrolling past title actions');
 await field.locator('.el-color-picker__trigger').click();const dropdown=page.locator('.el-color-dropdown:visible');await dropdown.locator('.el-color-dropdown__value input').fill('#DAECFA');await dropdown.getByRole('button',{name:'确定',exact:true}).click();
 async function assertPageColor(){assert.equal(await page.locator('.cart-preview').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(218, 236, 250)');assert.equal(await page.locator('.cart-preview-scroll').evaluate(el=>{const rect=el.getBoundingClientRect();let item=document.elementFromPoint(rect.left+110+100,rect.bottom-8);while(item){const color=getComputedStyle(item).backgroundColor;if(color!=='rgba(0, 0, 0, 0)' && color!=='transparent')return color;item=item.parentElement;}}),'rgb(218, 236, 250)','bottom whitespace shows configured page color');}
 await assertPageColor();await page.getByText('空购物车',{exact:true}).click();await assertPageColor();assert.equal(await page.locator('.cart-empty').count(),1);
 await page.getByRole('button',{name:'保存购物车页',exact:true}).click();await page.waitForFunction(()=>saved.length===1);assert.equal(await page.evaluate(()=>saved[0].value.background_color),'#DAECFA');await page.evaluate(()=>mountEditor());await page.waitForFunction(()=>!editor.loading);await page.locator('.el-loading-mask').waitFor({state:'hidden'});await assertPageColor();
 await page.locator('.cart-settings').evaluate(el=>{el.scrollTop=el.scrollHeight;});await page.locator('.page-editor-actions').getByRole('button',{name:'页面设置',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.cart-settings').scrollTop===0);
 await field.locator('.el-color-picker__trigger').click();await page.locator('.el-color-dropdown:visible').getByRole('button',{name:'清空',exact:true}).click();assert.equal(await page.evaluate(()=>editor.config.background_color),'#F5F5F5','clearing returns to valid default background');
 assert.deepEqual(errors,[]);console.log('PASS cart page background: discoverable picker, filled/empty whitespace, persistence, page-setting scroll and reset');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
