<?php
require __DIR__.'/commerce_bootstrap.php';
use think\facade\Db;
$notify=app()->make(app\services\pay\PayNotifyServices::class);
if(($argv[1]??'')==='worker'){
    if($argv[2]==='recharge')$ok=$notify->wechatUserRecharge('test-recharge-'.$argv[3],'synthetic-trade-'.$argv[3],'weixin');
    elseif($argv[2]==='member')$ok=$notify->wechatMember('test-member-'.$argv[3],'synthetic-member-trade-'.$argv[3],'weixin');
    elseif($argv[2]==='transfer')$ok=app()->make(app\services\user\UserRechargeServices::class)->importNowMoney(101,'20.00','same-transfer-request');
    elseif($argv[2]==='member_balance')$ok=app()->make(app\services\pay\YuePayServices::class)->yueOrderPay(Db::name('other_order')->where('id',1)->find(),101);
    else throw new RuntimeException('Unknown worker');
    if(!$ok)throw new RuntimeException('Callback failed');exit;
}
hardeningSchema();hardeningReset();
rechargeFixture(1,'50.00','5.00');
parallelCommerce([['recharge',1],['recharge',1],['recharge',1],['recharge',1]]);
checkCommerce(moneyValue()==='55.00'&&Db::name('user_money')->count()===1,'duplicate concurrent recharge credits once');
checkCommerce(Db::name('capital_flow')->count()===1&&Db::name('commerce_task')->count()===4,'one capital flow and four unique notification tasks');
hardeningReset();rechargeFixture(1,'50.00');rechargeFixture(2,'70.00');
parallelCommerce([['recharge',1],['recharge',2]]);
checkCommerce(moneyValue()==='120.00'&&Db::name('user_money')->count()===2,'two concurrent recharges preserve both balances and ledgers');
hardeningReset();rechargeFixture(1);
putenv('AUDIT_FAIL_LEDGER=1');checkCommerce(!$notify->wechatUserRecharge('test-recharge-1','x','weixin'),'ledger outage rejects callback');putenv('AUDIT_FAIL_LEDGER');
checkCommerce(moneyValue()==='0.00'&&!Db::name('user_recharge')->where('id',1)->value('paid')&&Db::name('commerce_task')->count()===0,'failed recharge rolls back paid balance and tasks');
checkCommerce($notify->wechatUserRecharge('test-recharge-1','x','weixin')&&moneyValue()==='50.00','recharge retry completes safely');
hardeningReset();memberFixture(1);
parallelCommerce([['member',1],['member',1],['member',1]]);
$expiry=(int)Db::name('user')->where('uid',101)->value('overdue_time');
checkCommerce(abs($expiry-time()-30*86400)<10&&Db::name('user_bill')->count()===1,'duplicate member callbacks grant exactly one term and ledger');
hardeningReset();memberFixture(1);
putenv('AUDIT_FAIL_LEDGER=1');checkCommerce(!$notify->wechatMember('test-member-1','x','weixin'),'member ledger outage rejects callback');putenv('AUDIT_FAIL_LEDGER');
checkCommerce(!Db::name('other_order')->where('id',1)->value('paid')&&!Db::name('user')->where('uid',101)->value('is_money_level'),'member failure rolls back payment and rights');
checkCommerce($notify->wechatMember('test-member-1','x','weixin')&&Db::name('user_bill')->count()===1,'member retry grants once');
hardeningReset();memberFixture(1);Db::name('user')->where('uid',101)->update(['is_money_level'=>1,'overdue_time'=>time()-60*86400]);
$notify->wechatMember('test-member-1','x','weixin');
checkCommerce(abs((int)Db::name('user')->where('uid',101)->value('overdue_time')-time()-30*86400)<10,'expired membership renews from purchase time');
hardeningReset();memberFixture(1);Db::name('user')->where('uid',101)->update(['is_money_level'=>1,'is_ever_level'=>1,'overdue_time'=>0]);
$notify->wechatMember('test-member-1','x','weixin');
checkCommerce((int)Db::name('user')->where('uid',101)->value('is_ever_level')===1,'term membership purchase cannot downgrade lifetime rights');
hardeningReset();memberFixture(1);Db::name('user')->where('uid',101)->update(['now_money'=>'100.00']);
parallelCommerce([['member_balance'],['member_balance'],['member_balance']]);
checkCommerce(moneyValue()==='80.00'&&Db::name('user_money')->count()===1&&Db::name('user_bill')->count()===1,'balance member payment retains one debit and one entitlement ledger');
hardeningReset();memberFixture(1);Db::name('user')->where('uid',101)->update(['is_promoter'=>1,'spread_open'=>1]);
$testSettings=['member_brokerage'=>1,'brokerage_func_status'=>1,'is_self_brokerage'=>1,'brokerage_level'=>1,'store_brokerage_ratio'=>10];
$notify->wechatMember('test-member-1','commission-case','weixin');$notify->wechatMember('test-member-1','commission-case','weixin');
checkCommerce(Db::name('user')->where('uid',101)->value('brokerage_price')==='202.00'&&Db::name('user_brokerage')->count()===1,'member callback commission is credited once');
$testSettings=[];
hardeningReset();
parallelCommerce([['transfer'],['transfer'],['transfer']]);
checkCommerce(moneyValue()==='20.00'&&Db::name('user')->where('uid',101)->value('brokerage_price')==='180.00'&&Db::name('commerce_operation')->count()===1,'commission transfer is atomic and idempotent by request key');
checkCommerce(Db::name('user_money')->count()===1&&Db::name('user_brokerage')->count()===1&&Db::name('user_extract')->count()===1,'commission transfer keeps all three audit records');
hardeningReset();rechargeFixture(1);putenv('AUDIT_FAIL_DELIVERY=1');
checkCommerce($notify->wechatUserRecharge('test-recharge-1','x','weixin')&&moneyValue()==='50.00','notification outage does not fail committed payment');
putenv('AUDIT_FAIL_DELIVERY');Db::name('commerce_task')->where('state','retry')->update(['next_attempt_at'=>0]);
app()->make(app\services\system\CommerceTaskServices::class)->tick();
checkCommerce(Db::name('commerce_task')->where('state','done')->count()===4,'pending notifications recover without another callback');
echo "Commerce database checks passed.\n";
