const assert = require('node:assert/strict');
const fs = require('node:fs'), path = require('node:path');
const root = path.resolve(__dirname, '../..'), deps = path.join(root, 'template/admin/node_modules');
const babel = require(path.join(deps, '@babel/core'));
function load(file, req = () => ({})) {
  let source = fs.readFileSync(path.join(root, file), 'utf8');
  if (file.endsWith('.vue')) source = source.match(/<script>([\s\S]*?)<\/script>/)[1];
  const code = babel.transformSync(source, { babelrc: false, configFile: false, plugins: [require(path.join(deps, '@babel/plugin-transform-modules-commonjs'))] }).code;
  const module = { exports: {} }; new Function('module', 'exports', 'require', code)(module, module.exports, req); return module.exports;
}
const shared = load('template/shared/pageActions.js');
const config = shared.headerActions({ left: [{ type: 'home' }], right: [{ type: 'collect' }, { type: 'share', label: '转发', showLabel: true }] });
assert.equal(config.left[0].label, '首页');
assert.equal(config.right[1].label, '转发');
assert.equal(shared.actionDisabled(config.right[0], {}), true, 'No product must disable collection');
assert.equal(shared.actionDisabled(config.right[0], { id: 22 }), false);
assert.equal(shared.actionDisabled(config.left[0], {}), false);
assert.equal(shared.actionLink({ type: 'home' }), '/pages/index/index');
assert.equal(shared.actionLink({ type: 'search' }), '/pages/goods/goods_search/index');
assert.equal(shared.actionLink({ type: 'link', link: '/pages/annex/special/index?id=7' }), '/pages/annex/special/index?id=7');
assert.equal(shared.actionLink({ type: 'link', link: 'javascript:alert(1)' }), '', 'Unsafe links never become executable actions');
const externalUrl = 'https://example.com/help?source=title&next=%2Fdocs#start';
assert.equal(shared.actionIcon({type:'link',icon:'icon-lianjie',link:'/pages/goods_cate/goods_cate'}),'icon-fenlei','legacy category links use the category icon');
assert.equal(shared.actionIcon({type:'url',icon:'icon-lianjie',link:'http://localhost:8011/pages/goods/goods_search/index?source=title'}),'icon-sousuo','URL search destinations use the search icon');
assert.equal(shared.actionIcon({type:'url',icon:'icon-lianjie',link:externalUrl}),'icon-baobeilianjie','generic URLs use the link glyph instead of a diagram connector');
assert.equal(shared.actionIcon({type:'link',icon:'icon-shoucang4',link:'/pages/goods_cate/goods_cate'}),'icon-shoucang4','explicit custom icons are preserved');
assert.equal(shared.actionIcon({type:'link',icon:'',link:'/pages/goods_cate/goods_cate'}),'','text-only buttons stay text-only');
assert.equal(shared.actionLink({ type: 'url', link: externalUrl }), externalUrl, 'URL buttons preserve query and fragment');
for (const link of ['javascript:alert(1)', 'data:text/html,test', '//example.com', 'https://', 'https://example.com/a b']) {
  assert.equal(shared.actionLink({ type: 'url', link }), '', 'URL buttons require an HTTP(S) address');
}
const independent = shared.headerActions(config); independent.left[0].label = '修改';
assert.equal(config.left[0].label, '首页', 'Editing one page must not alter the source template');
console.log('PASS page actions: left/right configuration, safe links, product requirements and independent page copies');
const Vue = require(path.join(deps, 'vue'));
const calls = [];
global.uni = { navigateTo: options => calls.push(['web', options.url]), navigateBack: options => options.fail(), setClipboardData: options => calls.push(['copy', options.data]) };
global.getCurrentPages = () => [{ route:'pages/goods_cate/goods_cate', $page:{fullPath:'/pages/goods_cate/goods_cate?sid=21'} }];
const component = load('template/uni-app/components/pageActionButtons/index.vue', id => id.includes('shared/') ? shared : id.includes('utils/') ? {getCustomer:path=>calls.push(['customer',path])} : {HTTP_REQUEST_URL:'https://mall.test'}).default;
const buttons = new Vue(component);
buttons.$util = {JumpPath: path => calls.push(['navigate',path])};
buttons.$on('action', action => calls.push(['action', action]));
buttons.activate(shared.pageAction({type:'collect'})); assert.equal(calls.length,0);
buttons.product = {id:22,userCollect:1};
buttons.activate(shared.pageAction({type:'collect'})); buttons.activate(shared.pageAction({type:'share'}));
assert.deepEqual(calls.splice(0),[['action','collect'],['action','share']]);
buttons.activate(shared.pageAction({type:'home'})); buttons.activate(shared.pageAction({type:'back'}));
assert.deepEqual(calls.splice(0),[['navigate','/pages/index/index'],['navigate','/pages/index/index']]);
buttons.activate(shared.pageAction({type:'customer'})); assert.deepEqual(calls.pop(),['customer','/pages/extension/customer_list/chat?productId=22']);
buttons.product = {}; buttons.activate(shared.pageAction({type:'share'}));
assert.deepEqual(calls.pop(),['copy','https://mall.test/pages/goods_cate/goods_cate?sid=21']);
buttons.activate(shared.pageAction({type:'search'}));
assert.deepEqual(calls.pop(),['navigate','/pages/goods/goods_search/index']);
buttons.activate(shared.pageAction({type:'cartManage'}));
assert.deepEqual(calls.pop(),['action','cartManage']);
buttons.activate(shared.pageAction({type:'url',link:externalUrl}));
assert.deepEqual(calls.pop(),['web','/pages/annex/web_view/index?url='+encodeURIComponent(externalUrl)]);
assert.equal(buttons.imageUrl('/uploads/icon.svg'),'https://mall.test/uploads/icon.svg');
buttons.$destroy();
console.log('PASS actual header actions: home/back navigation, current-product collect/share, customer context and page-link sharing');
