const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require('playwright');const {root,modules,bundle}=require('./theme_component_harness.cjs');
const {loadShared}=require('./ranking_shared_loader.cjs');const {canvasPreset,canvasNode,canvasDefaults}=loadShared('rankingCanvas');
const compiled=bundle('template/admin/src/components/themeActions/RankingCanvas.vue',['template/admin/src/components/themeActions/RankingCanvasEditor.vue','template/uni-app/subpackage/diyComponents/rankingCanvas.vue'],['@/config/app']);
for(const [file,r] of Object.entries(compiled.records))if(file.includes('/template/uni-app/')&&r.template)r.template=r.template.replace(/(<\/?)(view|text|image)(?=[\s>])/g,(_,p,t)=>p+({view:'div',text:'span',image:'img'}[t])).replace(/@tap(?=[.=:])/g,'@click');
const out=path.join(root,'.build/ranking-review');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1320,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.route('http://rank.test/**',route=>{const u=new URL(route.request().url());const file=u.pathname.startsWith('/statics/ranking/')?path.join(root,'crmeb/public',u.pathname):path.join(root,'template/admin/src/assets/images/product-diy.png');const ext=path.extname(file);return route.fulfill({headers:{'Access-Control-Allow-Origin':'*'},contentType:({'.svg':'image/svg+xml','.woff2':'font/woff2','.ttf':'font/ttf'})[ext]||'image/png',body:fs.readFileSync(file)});});
 await page.setContent('<div id="app"></div>');for(const file of ['vue/dist/vue.js','vuex/dist/vuex.js','element-ui/lib/index.js'])await page.addScriptTag({path:path.join(modules,file)});
 await page.addStyleTag({path:path.join(modules,'element-ui/lib/theme-chalk/index.css')});await page.addStyleTag({content:compiled.css+'body{margin:0;font-family:Arial,"Microsoft YaHei";background:#eee}*{box-sizing:border-box}.comparison{display:flex;gap:24px;padding:24px}.canvas-host{width:375px;flex-shrink:0}.canvas-title{font-size:15px;font-weight:600;padding:14px 0;color:#444}'});
 const scenes=['tmall_product','tmall_shop','dianping_shop'].map(canvasPreset);scenes[0].tabs=[{label:'热销榜',rankingId:9},{label:'好评榜',rankingId:10},{label:'新品榜',rankingId:11}];
 await page.evaluate(({compiled,scenes})=>{
   const cache={};const api={rankingList:async()=>({data:{list:[{id:9,name:'热销榜'},{id:10,name:'好评榜'},{id:11,name:'新品榜'}]}})};
   window.uni={createSelectorQuery(){let vm,selector,cb;return{in(v){vm=v;return this;},select(v){selector=v;return this;},boundingClientRect(v){cb=v;return this;},exec(){cb(vm.$el.getBoundingClientRect());}};},onWindowResize(){},offWindowResize(){},loadFontFace(options){const face=new FontFace(options.family,options.source);face.load().then(loaded=>{document.fonts.add(loaded);if(options.success)options.success();}).catch(error=>options.fail&&options.fail(error));}};
   window.loadCanvas=id=>{if(cache[id])return cache[id].exports;const r=compiled.records[id];if(!r)throw Error('Missing module '+id);const m=cache[id]={exports:{}};new Function('module','exports','require',r.code)(m,m.exports,name=>{if(name==='@/setting')return{apiBaseURL:'http://rank.test/adminapi'};if(name==='@/config/app')return{HTTP_REQUEST_URL:'http://rank.test'};if(name==='@/api/ranking')return api;if(/uploadPictures/.test(name))return{template:'<div />'};if(/\.png$/.test(name))return'http://rank.test/product.png';return loadCanvas(r.dependencies[name]);});if(r.template){Object.assign(m.exports.default,Vue.compile(r.template));m.exports.default._scopeId=r.scope;}return m.exports;};
   const file=suffix=>Object.keys(compiled.records).find(f=>f.endsWith(suffix));window.events=[];
   const rows=[1,2,3].map((rank)=>({id:rank,rank,name:['Apple iPad mini6 64G WLAN版','Apple iPad 平板电脑','Apple iPad mini6 256G'][rank-1],image:'http://rank.test/product.png',price:3799+rank*100,sales:2000-rank*300,score:9.9-rank/10,reviews:138,review_excerpt:'日常看书和学习使用，屏幕清晰。',rating_score:4.8,rating:98.5,type_name:'数码零售',product_count:36,products:[1,2,3].map((n)=>({id:rank*10+n,name:'平板电脑',image:'http://rank.test/product.png',price:n*100+3699,sales:n*100}))}));
   const config=scene=>({rankingId:9,limit:3,appearance:{canvas:JSON.parse(JSON.stringify(scene))}});const ranking={name:'平板电脑热销榜',description:'按近30天成交与评价排序',window_days:30,entity_type:'product'};
   window.vm=new Vue({components:{TestCanvas:loadCanvas(compiled.main).default,NativeCanvas:loadCanvas(file('/diyComponents/rankingCanvas.vue')).default,Editor:loadCanvas(file('/RankingCanvasEditor.vue')).default},data:{config:config(scenes[0]),ranking,rows,active:9,nativeKey:0,mode:'compare',editor:false,scenes},methods:{action(e){events.push(e);if(e.action==='tab')this.active=e.rankingId;}},template:'<div><div v-if="mode===\'compare\'" class="comparison"><div id="admin" class="canvas-host"><test-canvas :config="config" :rows="rows" :ranking="ranking" :active-board-id="active" @action="action" /></div><div id="native" class="canvas-host"><native-canvas :key="nativeKey" :config="config" :rows="rows" :ranking="ranking" :active-board-id="active" @action="action" /></div></div><div v-else class="comparison"><div v-for="(scene,index) in scenes" :key="index" class="canvas-host"><div class="canvas-title">{{[\'天猫商品榜 · 配置示例\',\'天猫店铺榜 · 配置示例\',\'点评店铺榜 · 配置示例\'][index]}}</div><test-canvas :config="{rankingId:9,limit:3,appearance:{canvas:scene}}" :rows="rows.map((row,i)=>index?({...row,name:[\'数码生活店\',\'智能设备店\',\'平板电脑店\'][i]}):row)" :ranking="{...ranking,name:index?\'数码店铺榜\':ranking.name,entity_type:index?\'shop\':\'product\'}" :active-board-id="9" /></div></div><editor v-if="editor" :config="config" :rows="rows" :ranking="ranking" @close="editor=false" /></div>'}).$mount('#app');
 },{compiled,scenes});
 await page.waitForFunction(()=>[...document.querySelectorAll('.rc-image')].every(img=>img.complete&&img.naturalWidth));
 const settled=()=>page.evaluate(async()=>{await new Promise(resolve=>{const check=()=>[...document.querySelectorAll('.ranking-canvas')].every(el=>el.dataset.fontsReady==='true')?resolve():requestAnimationFrame(check);check();});await document.fonts.ready;await Promise.all([...document.querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});
 await settled();
 const first=await page.locator('#admin .ranking-canvas').screenshot();await page.locator('#admin').evaluate(el=>el.style.display='none');await page.evaluate(async()=>{vm.nativeKey++;await Vue.nextTick();});await page.waitForFunction(()=>[...document.querySelectorAll('#native .rc-image')].every(img=>img.complete&&img.naturalWidth));await settled();const native=await page.locator('#native .ranking-canvas').screenshot();await page.locator('#admin').evaluate(el=>el.style.display='block');fs.writeFileSync(path.join(out,'canvas-admin.png'),first);fs.writeFileSync(path.join(out,'canvas-native.png'),native);const {PNG}=require('pngjs');const a=PNG.sync.read(first),b=PNG.sync.read(native);assert(a.width===b.width&&a.height===b.height&&a.data.equals(b.data),'same canvas configuration must produce the same pixels in HTML and Uni tag adapters at the same viewport position');

 for(const index of [1,2]){await page.evaluate(async index=>{vm.config.appearance.canvas=JSON.parse(JSON.stringify(vm.scenes[index]));await Vue.nextTick();},index);await page.waitForFunction(()=>[...document.querySelectorAll('.rc-image')].every(img=>img.complete&&img.naturalWidth));await settled();const left=PNG.sync.read(await page.locator('#admin .ranking-canvas').screenshot());await page.locator('#admin').evaluate(el=>el.style.display='none');await page.evaluate(async()=>{vm.nativeKey++;await Vue.nextTick();});await page.waitForFunction(()=>[...document.querySelectorAll('#native .rc-image')].every(img=>img.complete&&img.naturalWidth));await settled();const right=PNG.sync.read(await page.locator('#native .ranking-canvas').screenshot());await page.locator('#admin').evaluate(el=>el.style.display='block');assert(left.width===right.width&&left.height===right.height&&left.data.equals(right.data),'preset '+index+' adapter pixels must match');if(index===1){await page.locator('#admin [data-node-id="店铺商品组"] .rc-image').first().click();assert.equal(await page.evaluate(()=>events.at(-1).item.id),11);}}
 await page.evaluate(async()=>{vm.config.appearance.canvas=JSON.parse(JSON.stringify(vm.scenes[0]));await Vue.nextTick();});
 await page.evaluate(async()=>{vm.config=JSON.parse(JSON.stringify(vm.config));await Vue.nextTick();});assert(first.equals(await page.locator('#admin .ranking-canvas').screenshot()),'export/import must preserve exact rendered pixels');

 // Opaque high-z images may cover the row and nested elements, but never their outlines.
 const borderScene=canvasDefaults();borderScene.enabled=true;borderScene.header.height=0;borderScene.card.height=240;borderScene.card.gap=0;
 borderScene.card.nodes=[
  canvasNode('group',{id:'row-outline',style:{width:375,height:240,borderWidth:6,borderColor:'#ff0000',radiusTL:16,radiusTR:16,radiusBR:16,radiusBL:16},rankStyles:[{from:2,to:2,style:{borderColor:'#00ffff'}}]}),
  canvasNode('image',{id:'image-outline',binding:'item.image',style:{x:32,y:30,width:100,height:100,borderWidth:5,borderColor:'#00ff00'}}),
  canvasNode('group',{id:'nested-outline',style:{x:180,y:40,width:140,height:130,borderWidth:4,borderColor:'#ffff00'},children:[canvasNode('group',{id:'child-outline',style:{x:20,y:20,width:70,height:50,borderWidth:4,borderColor:'#ff00ff'}})]}),
  canvasNode('image',{id:'covering-photo',binding:'item.image',action:'product',style:{width:375,height:240,zIndex:999,fit:'fill'}}),
 ];
 await page.evaluate(async scene=>{vm.config.appearance.canvas=scene;vm.config.limit=2;await Vue.nextTick();},borderScene);await settled();
 const pixel=(png,x,y)=>[...png.data.subarray((y*png.width+x)*4,(y*png.width+x)*4+3)];
 for(const host of ['admin','native']){
  const shot=PNG.sync.read(await page.locator('#'+host+' .ranking-canvas').screenshot());
  for(const [x,y,color] of [[2,60,[255,0,0]],[200,2,[255,0,0]],[372,60,[255,0,0]],[200,237,[255,0,0]],[34,60,[0,255,0]],[80,32,[0,255,0]],[182,90,[255,255,0]],[220,66,[255,0,255]],[2,300,[0,255,255]]])assert.deepEqual(pixel(shot,x,y),color,host+' topmost outline '+x+','+y);
  await page.locator('#'+host+' [data-node-id="covering-photo"]').first().click({position:{x:2,y:60}});assert.equal(await page.evaluate(()=>events.at(-1).item.id),1,'outlines must not intercept product taps');
 }
 await page.locator('#admin .ranking-canvas').screenshot({path:path.join(out,'topmost-borders.png')});
 await page.evaluate(async()=>{vm.config.appearance.canvas.card.nodes[2].visible=false;await Vue.nextTick();});assert.equal(await page.locator('#admin [data-border-id="child-outline"]').count(),0,'hidden parents also hide descendant outlines');
 await page.evaluate(async()=>{vm.config.appearance.canvas=JSON.parse(JSON.stringify(vm.scenes[1]));vm.config.limit=3;const group=vm.config.appearance.canvas.card.nodes.find(n=>n.kind==='products');Object.assign(group.style,{paddingX:4,paddingY:3,borderWidth:2,borderColor:'#cc0000'});Object.assign(group.productNodes[0].style,{borderWidth:3,borderColor:'#008800'});await Vue.nextTick();});await settled();
 for(const host of ['admin','native']){const bounds=await page.locator('#'+host+' [data-node-id="店铺商品组"] .rc-image').first().evaluate(el=>{const photo=el.parentElement,outline=document.querySelector('#'+el.closest('.canvas-host').id+' [data-border-id="'+photo.dataset.nodeId+'"]');const a=photo.getBoundingClientRect(),b=outline.getBoundingClientRect();return ['x','y','width','height'].map(key=>Math.abs(a[key]-b[key]));});assert(bounds.every(n=>n<.01),'scaled nested product borders align with image edges');}
 await page.evaluate(async()=>{vm.config.appearance.canvas=JSON.parse(JSON.stringify(vm.scenes[0]));await Vue.nextTick();});await settled();
 await page.locator('#admin .rc-tabs button').nth(1).click();assert.equal(await page.evaluate(()=>events.at(-1).rankingId),10);assert.equal(await page.locator('#admin .rc-tabs button').nth(1).evaluate(el=>getComputedStyle(el).color),'rgb(245, 215, 160)');
 await page.locator('#admin [data-node-id="购买按钮"]').first().click();assert.equal(await page.evaluate(()=>events.at(-1).item.id),1);
 await page.evaluate(async()=>{vm.editor=true;await Vue.nextTick();});await page.locator('.rc-layer-entry>button').filter({hasText:'商品名称'}).click();await page.locator('.rc-inspector [data-field="x"] input').fill('171');await page.locator('.rc-inspector [data-field="x"] input').press('Tab');assert.equal(await page.evaluate(()=>vm.config.appearance.canvas.card.nodes.find(n=>n.id==='商品名称').style.x),171);
 await page.getByRole('button',{name:'添加名次覆盖',exact:true}).click();await page.locator('.rc-inspector [data-field="x"] input').fill('182');await page.locator('.rc-inspector [data-field="x"] input').press('Tab');assert.equal(await page.evaluate(()=>vm.config.appearance.canvas.card.nodes.find(n=>n.id==='商品名称').rankStyles[0].style.x),182);assert.equal(await page.evaluate(()=>vm.config.appearance.canvas.card.nodes.find(n=>n.id==='商品名称').style.x),171);

 await page.getByRole('button',{name:'整行背景与边框',exact:true}).click();await page.locator('.rc-inspector [data-field="borderWidth"] input').fill('3');await page.locator('.rc-inspector [data-field="borderWidth"] input').press('Tab');assert.equal(await page.locator('.rc-editor-preview [data-border-id="商品卡片背景"]').evaluate(el=>getComputedStyle(el).borderTopWidth),'3px');
 // Drive the real inspector: visibility, bound metric, affixes, type size and header labels.
 await page.locator('.rc-editor-preview [data-node-id="更多按钮"]').click();await page.locator('[data-content-field="text"] textarea').fill('榜单说明');await page.locator('.rc-inspector [data-field="fontSize"] input').fill('14');await page.locator('.rc-inspector [data-field="fontSize"] input').press('Tab');assert.equal(await page.locator('#admin [data-node-id="更多按钮"] .rc-text').textContent(),'榜单说明');assert.equal(await page.locator('#native [data-node-id="更多按钮"]').evaluate(el=>getComputedStyle(el).fontSize),'14px');
 await page.locator('.rc-layer-entry[data-layer-id="更多按钮"] .el-switch').click();assert.equal(await page.locator('#admin [data-node-id="更多按钮"]').count(),0);assert.equal(await page.locator('#native [data-border-id="更多按钮"]').count(),0);await page.locator('.rc-layer-entry[data-layer-id="更多按钮"] .el-switch').click();
 await page.evaluate(async()=>{vm.config.appearance.canvas=JSON.parse(JSON.stringify(vm.scenes[1]));await Vue.nextTick();});await settled();await page.locator('.rc-editor-preview [data-node-id="在售商品数"]').click();
 await page.locator('[data-content-field="affixes"] input').nth(0).fill('当前在售 ');await page.locator('[data-content-field="affixes"] input').nth(1).fill(' 款');await page.locator('.rc-inspector [data-field="fontSize"] input').fill('15');await page.locator('.rc-inspector [data-field="fontSize"] input').press('Tab');
 assert.equal(await page.locator('#native [data-node-id="在售商品数"] .rc-text').first().textContent(),'当前在售 36 款');assert.equal(await page.locator('#admin [data-node-id="在售商品数"]').first().evaluate(el=>getComputedStyle(el).fontSize),'15px');
 await page.locator('[data-content-field="binding"] .el-select').click();await page.locator('.el-select-dropdown:visible .el-select-dropdown__item').filter({hasText:/^评价数$/}).click();assert.equal(await page.locator('#native [data-node-id="在售商品数"] .rc-text').first().textContent(),'当前在售 138 款');
 await page.locator('.rc-layer-entry[data-layer-id="评价数量"] .el-switch').click();assert.equal(await page.locator('#native [data-node-id="评价数量"]').count(),0);assert.equal(await page.locator('#admin [data-node-id="在售商品数"]').count(),3,'other metrics stay visible');
 await page.getByRole('button',{name:'返回装修',exact:true}).click();await page.locator('.v-modal').waitFor({state:'hidden'});await page.evaluate(()=>{vm.mode='gallery';});await page.waitForFunction(()=>[...document.querySelectorAll('.rc-image')].every(img=>img.complete&&img.naturalWidth));await settled();await page.screenshot({path:path.join(out,'ranking-canvas-presets.png'),fullPage:true});await page.locator('.comparison > .canvas-host').nth(2).evaluate(el=>el.style.display='none');await page.setViewportSize({width:822,height:1020});await settled();await page.screenshot({path:path.join(out,'tmall-configured.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log('PASS: exact adapter screenshot parity, exact JSON round-trip pixels, tab and purchase actions, topmost row/image/nested borders, scaled product borders, editable content/visibility, real inspector updates and per-rank inheritance');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
