const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { bundle, install } = require('./theme_component_harness.cjs');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1500, height: 960 } });
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await install(page, bundle('template/admin/src/pages/setting/theme/editTheme/components/CategoryEditor.vue'));
    await page.waitForFunction(() => !editor.loading);
    await page.locator('.module-grid button').nth(5).click();
    await page.getByRole('tab', { name: '样式设置', exact: true }).click();
    const corners = page.locator('.checkout-settings .margin-style-config').filter({ hasText: '背景圆角' });
    const total = corners.locator('.main-setting input');
    await total.fill('28');
    await page.waitForFunction(() => getComputedStyle(document.querySelector('.checkout-preview-surface')).borderTopLeftRadius === '28px');
    await corners.locator('.expand-icon').click();
    await total.fill('29'); await total.press('Enter');
    await page.waitForTimeout(100);
    assert.deepEqual(await page.evaluate(() => editor.config.checkout.fillet.valList.map(item => item.val)), [29, 29, 29, 29], 'the overall radius control must update expanded corners');
    assert.equal(await page.locator('.checkout-preview-surface').evaluate(el => getComputedStyle(el).borderTopLeftRadius), '29px');
    await corners.locator('.sub-settings input').nth(0).fill('12');
    await corners.locator('.sub-settings input').nth(0).press('Enter');
    await page.getByRole('button', { name: '保存分类页' }).click();
    await page.evaluate(() => mountEditor()); await page.waitForFunction(() => !editor.loading);
    assert.deepEqual(await page.evaluate(() => editor.config.checkout.fillet.valList.map(item => item.val)), [12, 29, 29, 29], 'loading asymmetric corners must preserve them');
    await page.locator('.module-grid button').nth(5).click();
    await page.getByRole('tab', { name: '内容设置', exact: true }).click();
    assert.equal(await page.locator('.checkout-icon-preview img').count(), 2, 'both default icon states are visible in settings');
    await page.getByText('文字+图标', { exact: true }).click();
    assert.equal(await page.locator('.checkout-cart img').count(), 1);
    assert.match(await page.locator('.checkout-cart').innerText(), /购物车/);
    await page.getByText('选中后', { exact: true }).click();
    assert.match(await page.locator('.checkout-cart img').getAttribute('src'), /3-002/);
    await page.evaluate(()=>{editor.config.checkout.iconImage='/uploads/custom-cart.png';editor.config.checkout.activeIconImage='/uploads/custom-active.png';});
    await page.locator('.checkout-icon-preview').nth(1).getByText('恢复默认',{exact:true}).click();
    assert.match(await page.locator('.checkout-cart img').getAttribute('src'),/3-002/,'resetting selected icon must not reuse a custom unselected icon');
    await page.getByText('仅文字', { exact: true }).click();
    assert.equal(await page.locator('.checkout-cart img').count(), 0);
    await page.getByRole('button', { name: '保存分类页' }).click();
    await page.evaluate(() => mountEditor()); await page.waitForFunction(() => !editor.loading);
    assert.equal(await page.evaluate(() => editor.config.checkout.cartDisplay), 'text');
    await page.locator('.module-grid button').nth(5).click();
    await page.getByRole('tab', { name: '内容设置', exact: true }).click();
    await page.getByText('悬浮胶囊', { exact: true }).click();
    await page.getByText('选中后', { exact: true }).click();
    const surface = page.locator('.checkout-preview-surface');
    assert.equal(await surface.evaluate(el=>getComputedStyle(el).borderRadius),'24px');
    assert.equal(await surface.evaluate(el=>getComputedStyle(el).marginLeft),'10px');
    assert.match(await surface.evaluate(el=>getComputedStyle(el).backgroundImage),/48, 48, 48/);
    assert.equal(await page.locator('.checkout-details').innerText(),'查看明细⌃');
    assert.match(await page.locator('.checkout-preview b').innerText(),/\(2\)/);
    const floated = await surface.boundingBox();
    assert.equal(floated.height,38,'floating checkout matches the compact reference');
    assert.deepEqual(errors, []);
    console.log('PASS decoration controls: expanded radius, asymmetric reload, two icon states and text/icon modes');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });

